# Generated by Django 6.0.3 on 2026-03-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=10),
        ),
    ]
